config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :entities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @entities = client.entities
  end

  def show
    @entity = client.entity(thing: safe_params[:id], filters: safe_params[:filters].to_h)
  end

  private

  def client
    @client ||= Services::CrmClient.new
  end

  def safe_params
    params.permit(:id, filters: [:emailaddress1])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/index.html.erb
<p>
  @odata.context <%= @entities["@odata.context"] %>
</p>

<p>
  <% @entities["value"].each do |node| %>
    <ul>
      <li>name: <%= node["name"] %></li>
      <li>kind: <%= node["kind"] %></li>
      <li>url: <%= link_to node["url"], entity_path(node["url"]) %></li>
    </ul>

    <br>
  <% end %>
</p>

app/views/entities/show.html.erb
<p>
  @odata.context <%= @entity["@odata.context"] %>
</p>

<% @entity["value"].each do |hash| %>
  <table>
    <% hash.each do |k,v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td>
      </tr>
    <% end %>
  </table>

  ===
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PanellistPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>